### ISSUE TITLE
[FibaroHC] power is not a number in logs

### ISSUE THREAD

**Issue by nickhandel** [ilcato/homebridge-fibaro-home-center#403] opened 2024-06-29 12:50 UTC
Hello - my HB logs are full of this error message [FibaroHC] power is not a number. 

Is there a way to get some more detail on this (i.e. from which device it originates)?

Thanks

Nick

**Comment by mkz212** [comment] 2024-06-29 13:08
@nickhandel 

If you have any issues with this plugin, enable all logs in plugin config and the debug mode in the homebridge settings and restart the homebridge / child bridge. This will show additional information in log.

**Comment by mkz212** [comment] 2024-06-29 15:29
@nickhandel Most probably such an error is caused by Wall Plug or Walli Outlet. Please attach here response from API for this device (how to get api response you can find in Plugin homepage).

**Comment by nickhandel** [comment] 2024-07-07 18:41
Thanks for that - I think I found it - I have eight HeatIt Z-Smoke detectors and for some reason the smoke alarm test device (which used to be showing up as a switch) is now showing as a power outlet. 
I removed them from HomeKit by removing access from the Fibaro user used by HomeKit and the messages have stopped.

**Comment by mkz212** [comment] 2024-07-08 05:23
@nickhandel 

I'm glad it helped. Please close this Issue. 

If you want, you can open a new Issue chosing New Device template to report this device to be supported.

**Closed** 2024-07-08 07:08 UTC
